name: Deploy Svelte App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version suitable for your Svelte project

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Svelte project
        run: pnpm run build

      - name: Deploy built files via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/*"
          target: ${{ secrets.DEPLOY_PATH }}
          # Ensures that the target directory on the server is cleaned before new files are copied.
          # Use with caution, as it will delete existing files in DEPLOY_PATH.
          # rsync_options: "-az --delete"

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Deployment successful! Verifying files in ${{ secrets.DEPLOY_PATH }}..."
            ls -la ${{ secrets.DEPLOY_PATH }}
            # You might want to also check for specific files, e.g.,
            # ls -la ${{ secrets.DEPLOY_PATH }}/index.html
